### ISSUE TITLE
my contribs 

### ISSUE THREAD

**Issue by GenericCoding** [Lrdsnow/kfd_offsets#1]
got the tool working but still has a crash I think from debugging the offsets generated are wrong (due to a bug with the tihmstar tool) 
https://github.com/GenericCoding/offsets/blob/main/iphone13.1_16.12/gen.h -- feel free to add here I can git clone this and continue adding if the tool gets fixed and I can get kfd working on my device

**Comment by matteozappia** [comment]
@GenericCoding can u dm me on twitter?

**Comment by GenericCoding** [comment]
@matteozappia sure i just made an account and followed you, you can dm if you want

**Comment by matteozappia** [comment]
can't find u, what's your @?

**Comment by GenericCoding** [comment]
@matteozappia GenericCoding

**Comment by GenericCoding** [comment]
@matteozappia ./autogen.sh —with-offsetexporter —without-img3tool —without-img4tool

**Comment by Lrdsnow** [comment]
> got the tool working but still has a crash I think from debugging the offsets generated are wrong (due to a bug with the tihmstar tool)
> https://github.com/GenericCoding/offsets/blob/main/iphone13.1_16.12/gen.h -- feel free to add here I can git clone this and continue adding if the tool gets fixed and I can get kfd working on my device

If it is a bug with the tihmstar tool I’ll redo all of the offsets once it’s fixed I’ve saved all of the kernels for all the versions on this repo so, also I’ve noticed that you put iPhone13,1 (iPhone 12 mini) Was that intentional?

**Comment by Lrdsnow** [comment]
> @matteozappia ./autogen.sh —with-offsetexporter —without-img3tool —without-img4tool

Also one thing to note is that you don’t need `--without-img3tool` or `--without-img4tool` on Intel Mac’s because img3tool and img4tool build perfectly on Intel Macs

**Comment by GenericCoding** [comment]
@Lrdsnow My friend on Discord said this worked 
https://github.com/tihmstar/libpatchfinder/pull/26
but i haven't been able to try it yet, he tried the fork after with the fun.h functions, and all of them but the csflags (which crashed) worked.

**Comment by Lrdsnow** [comment]
Also isn’t fun.h only from this fork https://github.com/wh1te4ever/kfd?

**Comment by GenericCoding** [comment]
@Lrdsnow yes, he just manually modified the offset arrays and didn't use the other branch, i've attempted to build both ways and both are feasible, ideally it would be cool if the commit which changes how offsets are stored could be reconciled with the wh1te4ever source. I'll look into it tomorrow when I have access to my mac.

**Comment by hrtowii** [comment]
Hi, said friend here. I will be publishing my version on Github. to clear up any misconceptions, i AM using the branch of kfd with dynamic_info (which is kern-version); i just used tihmstar's libpatchfinder and changed the 0x8's to 0x10s.

**Comment by GenericCoding** [comment]
@hrtowii yay, did you just import fun then?

**Comment by Lrdsnow** [comment]
> @Lrdsnow yes, he just manually modified the offset arrays and didn't use the other branch, i've attempted to build both ways and both are feasible, ideally it would be cool if the commit which changes how offsets are stored could be reconciled with the wh1te4ever source. I'll look into it tomorrow when I have access to my mac.

I agree and Ive built the patch for libpatchfinder all will push all the new blobs in a second, while I’m at it would you like me to add your iPhone 12 mini on 16.1.2?

**Comment by hrtowii** [comment]
Yes, I just copied fun.c and .h into the project @GenericCoding

**Comment by Lrdsnow** [comment]
> 

So should I change this for all offsets I get from the patched libpatchfinder?

**Comment by Lrdsnow** [comment]
I’ve tried with the new patched libpatchfinder and with changing the 0x8’s to 0x10’s yet I just get a kernel panic

**Comment by Lrdsnow** [comment]
Also you mentioned you had a discord @GenericCoding?

**Comment by GenericCoding** [comment]
@Lrdsnow ya .blahblahblahblah

**Comment by Lrdsnow** [comment]
> @Lrdsnow ya .blahblahblahblah

I sent you a friend request

**Comment by moqi2011** [comment]
@Lrdsnow add me on twitter @xiaopan37057090
