### ISSUE TITLE
Where are the offsets of iPads?

### ISSUE THREAD

**Issue by ZZY3312** [Lrdsnow/kfd_offsets#6]
There are no offsets for iPads. I hope you can add it.

**Comment by Lrdsnow** [comment]
What iPad offsets do you need?

**Comment by ZZY3312** [comment]
iPad Pro (11-inch 3rd generation) on iPadOS 16.6 dev beta 1发自我的 iPad在 2023年7月29日，13:32，Lrdsnow ***@***.***> 写道：﻿
What iPad offsets do you need?

**Comment by ZZY3312** [comment]
iPad13,6(iPad Pro 11-in 3rd gen) 16.6 dev beta 1

**Comment by Lrdsnow** [comment]
Added https://github.com/Lrdsnow/kfd_offsets/tree/main/iPad13%2C6
If you have any issues try messaging me on discord, my username is lrdsnow
